#!/bin/sh
# seo.sh — generate the crawler-facing files for the docs site, and gate them.
#
#   scripts/seo.sh render    write sitemap.xml, robots.txt and llms.txt
#   scripts/seo.sh check     fail if they disagree with the page (CI gate)
#
# Everything here fails *silently*: a sitemap naming an old URL, a canonical
# that drifted, a JSON-LD block truncated by an edit. The page still renders and
# the only symptom is that it stops being found. So the files are generated from
# the page rather than maintained beside it, and a disagreement is a build
# failure.
#
# Why the sitemap is mechanical rather than hygiene here: crawlers read
# robots.txt only from the host root, and allan-nava.github.io's robots.txt
# generates one `Sitemap:` line per project site whose /<repo>/sitemap.xml
# answers **200**, from a daily sync that enumerates the owner's Pages repos. No
# list to maintain and nothing to declare — but a site that ships no sitemap is
# simply absent, which segcheck was. Ours is also the file actually served the
# day this moves to a domain of its own.
#
# POSIX sh and awk only, like the rest of scripts/. SEO_DIR and CHANGELOG_FILE
# point at a fixture.
set -eu

root=$(CDPATH= cd -- "$(dirname -- "$0")/.." && pwd)
dir="${SEO_DIR:-$root/docs}"
changelog="${CHANGELOG_FILE:-$root/CHANGELOG.md}"
mode="${1:-check}"

html="$dir/index.html"
[ -f "$html" ] || { echo "seo.sh: no such file: $html" >&2; exit 2; }
[ -f "$changelog" ] || { echo "seo.sh: no such file: $changelog" >&2; exit 2; }

# The newest *released* version. [Unreleased] is not something llms.txt can
# describe: it would name a release nobody can install.
version=$(awk '/^## \[/ {
	i = index($0, "["); j = index($0, "]")
	v = substr($0, i + 1, j - i - 1)
	if (tolower(v) == "unreleased") next
	print v; exit
}' "$changelog")
[ -n "$version" ] || { echo "seo.sh: CHANGELOG.md names no released version" >&2; exit 1; }

attr() {
	awk -v pat="$1" '
		$0 ~ pat {
			for (k = 1; k <= 2; k++) {
				key = (k == 1) ? "href=\"" : "content=\""
				i = index($0, key)
				if (i) { r = substr($0, i + length(key)); j = index(r, "\""); print substr(r, 1, j - 1); exit }
			}
		}
	' "$html"
}

canonical=$(attr 'rel="canonical"')
[ -n "$canonical" ] || { echo "seo.sh: the page has no rel=canonical" >&2; exit 1; }
case "$canonical" in */) ;; *) canonical="$canonical/" ;; esac

title=$(awk -F'[<>]' '/<title>/ { print $3; exit }' "$html")
desc=$(attr 'name="description"')

render() {
	today=$(date +%Y-%m-%d)

	cat > "$dir/sitemap.xml" <<XML
<?xml version="1.0" encoding="UTF-8"?>
<!-- Generated by scripts/seo.sh — do not edit by hand. -->
<urlset xmlns="http://www.sitemaps.org/schemas/sitemap/0.9">
  <url>
    <loc>$canonical</loc>
    <lastmod>$today</lastmod>
    <changefreq>weekly</changefreq>
    <priority>1.0</priority>
  </url>
</urlset>
XML

	cat > "$dir/robots.txt" <<TXT
# Generated by scripts/seo.sh — do not edit by hand.
#
# On a GitHub project page this file sits at /segcheck/robots.txt, and crawlers
# read only the host root's — https://allan-nava.github.io/robots.txt, which
# generates its Sitemap: lines from the project sitemaps that answer 200, this
# one included. This file is the local source of truth the SEO gate checks
# against, and the one actually served if this moves to a domain of its own.
User-agent: *
Allow: /
Disallow:

Sitemap: ${canonical}sitemap.xml
TXT

	cat > "$dir/llms.txt" <<TXT
# segcheck $version

> $desc

Documentation: $canonical
Source: https://github.com/Allan-Nava/segcheck

## What it is

segcheck downloads HLS and DASH media segments, parses their bytes, and
compares the media against the manifest. Point it at an HLS master playlist or a
DASH MPD and it reports the defects a manifest cannot express: segments that do not join up, a 1080p rung
that codes 720p, declared durations that drift from the real ones, renditions
that are not on a shared timeline. One static Go binary, zero dependencies.

## What it checks

Each check compares what the manifest declares against what the bytes contain:

- manifest — the manifest parses, and what shape it is
- fetch — every sampled segment is reachable, and none was truncated by the byte cap
- init — the EXT-X-MAP / DASH initialisation segment is available
- container — the bytes are the media they claim to be; an origin error page served with a 200 lands here
- continuity — each segment starts where the previous one ended, and MPEG-TS continuity-counter breaks
- duration — declared EXTINF / @d against the real media duration, per segment and accumulated
- discontinuity — EXT-X-DISCONTINUITY against the timeline reset it promises, and the sequence across the ladder
- timeline — a DASH SegmentTimeline @t against the fragment's tfdt
- bitrate — measured peak and average against the declared BANDWIDTH, in both directions
- resolution — the coded resolution in the bitstream against the declared RESOLUTION
- keyframe — every segment carries a random access point, so it can be switched into at all
- alignment, ladder, codecstring, encryption, captions, audio, dvr and more

## Statuses

OK, WARN, BAD and ERROR, worst first in every renderer. ERROR sorts above BAD:
a check that could not run is not a check that passed.

## Pages

- ${canonical} — everything: what it checks, install, flags, output, sampling
- ${canonical}running-in-containers.html — running it from the image
- https://github.com/Allan-Nava/segcheck/blob/main/BACKLOG.md — planned work, with stable SC-n ids
- https://github.com/Allan-Nava/segcheck/blob/main/CHANGELOG.md — what changed, per tagged release

## Not

Not a player and not an encoder QC suite: it reads the bytes that are published
and compares them with what the manifest says about them. Sibling tools:
checkfleet (fleet and certificate checks), pqprobe (which classes of TLS client
can still handshake with an endpoint), crowdsim (load, safely).
TXT

	printf 'wrote sitemap.xml, robots.txt and llms.txt for %s\n' "$canonical"
}

check() {
	bad=0
	err() { printf 'seo.sh: %s\n' "$1" >&2; bad=$((bad + 1)); }

	for pat in 'name="description"' 'name="robots"' 'rel="canonical"' 'property="og:image"' 'property="og:title"'; do
		grep -q "$pat" "$html" || err "the page has no $pat"
	done
	[ -n "$title" ] || err "the page has no <title>"
	[ -n "$desc" ] || err "the page has no description"

	n=$(printf '%s' "$desc" | wc -c | tr -d ' ')
	if [ -n "$desc" ] && { [ "$n" -lt 70 ] || [ "$n" -gt 320 ]; }; then
		err "the description is $n characters; aim for 70-320"
	fi

	if ! grep -q 'application/ld+json' "$html"; then
		err "the page carries no JSON-LD"
	else
		ld=$(awk '/application\/ld\+json/ { inside = 1; next } /<\/script>/ { inside = 0 } inside' "$html")
		opens=$(printf '%s' "$ld" | tr -cd '{' | wc -c | tr -d ' ')
		closes=$(printf '%s' "$ld" | tr -cd '}' | wc -c | tr -d ' ')
		[ "$opens" -gt 0 ] || err "the JSON-LD block is empty"
		[ "$opens" = "$closes" ] || err "the JSON-LD braces do not balance ($opens open, $closes closed) — an edit truncated it"
		printf '%s' "$ld" | grep -q "$canonical" || err "the JSON-LD does not name $canonical"
	fi

	for f in sitemap.xml robots.txt llms.txt; do
		[ -f "$dir/$f" ] || err "docs/$f is missing — run scripts/seo.sh render"
	done
	[ -f "$dir/sitemap.xml" ] && { grep -q "<loc>$canonical</loc>" "$dir/sitemap.xml" ||
		err "sitemap.xml does not name $canonical — run scripts/seo.sh render"; }
	# Every URL in the sitemap has to have a file behind it. The first version of
	# this sitemap listed running-in-containers.html, and Pages serves docs/ as
	# committed: the .md is 200 and the .html is 404. A declared URL that does
	# not exist wastes crawl budget, which is the same reason the host root only
	# lists sitemaps that answer 200.
	if [ -f "$dir/sitemap.xml" ]; then
		awk -F'[<>]' '/<loc>/ { print $3 }' "$dir/sitemap.xml" | while IFS= read -r loc; do
			rel=${loc#"$canonical"}
			case "$rel" in
			"" ) path="index.html" ;;
			*/ ) path="$rel/index.html" ;;
			* )  path="$rel" ;;
			esac
			[ -e "$dir/$path" ] || printf '%s -> %s\n' "$loc" "$path"
		done > "$dir/.seo-missing.$$"
		if [ -s "$dir/.seo-missing.$$" ]; then
			while IFS= read -r line; do
				err "the sitemap declares a URL with no file behind it: $line"
			done < "$dir/.seo-missing.$$"
		fi
		rm -f "$dir/.seo-missing.$$"
	fi

	[ -f "$dir/robots.txt" ] && { grep -q "Sitemap: ${canonical}sitemap.xml" "$dir/robots.txt" ||
		err "robots.txt does not point at ${canonical}sitemap.xml"; }
	[ -f "$dir/llms.txt" ] && { grep -q "segcheck $version" "$dir/llms.txt" ||
		err "llms.txt does not describe $version — run scripts/seo.sh render"; }

	if [ "$bad" -gt 0 ]; then
		printf '\n%d SEO problem(s)\n' "$bad" >&2
		exit 1
	fi
	printf 'seo OK — %s, %d-character description, sitemap and llms.txt in step\n' "$canonical" "$n"
}

case "$mode" in
render) render ;;
check)  check ;;
*) echo "usage: scripts/seo.sh [render|check]" >&2; exit 2 ;;
esac
